#!/usr/bin/env zsh
# ZSH AutoSuggestions
ZSH_AUTOSUGGEST_USE_ASYNC=1
source "$ZSH_CONFIG/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"


# Syntax highlighter, source close to last
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES[alias]='bg=blue'
ZSH_HIGHLIGHT_STYLES[function]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=yellow'
source "$ZSH_CONFIG/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# History Substring Search
source "$ZSH_CONFIG/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh"
