#!/usr/bin/env zsh
# ZSH AutoSuggestions
ZSH_AUTOSUGGEST_USE_ASYNC=1
source "$ZSH_CONFIG/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"

# History Substring Search
source "$ZSH_CONFIG/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh"

# Syntax highlighter, source last
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
source "$ZSH_CONFIG/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
