#!/usr/bin/env bash

if [[ "${OSTYPE}" == "darwin"* ]]; then
  # Add homebrew and coreutils stuff for macOSj 
  export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}"
  export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:${MANPATH}"

  # Turn off analytics for homeberw
  export HOMEBREW_NO_ANALYTICS=1
fi

# start in tmux session unless already in a tmux session
# or in an SSH session
if [ -z "${TMUX}" ] && [ -z "${SSH_CLIENT}" ] && [ -z "${SSH_TTY}" ]; then 
  if command tmux -V >/dev/null 2>&1; then
    TMUX_LOG_DIR="${XDG_DATA_HOME}/tmux/log"
    TMUX_SESSION_ID="${${TERM_SESSION_ID%%:*}:-${KITTY_WINDOW_ID}}"
    cd "${TMUX_LOG_DIR}" || { mkdir -p "${TMUX_LOG_DIR}" && cd "${TMUX_LOG_DIR}" || exit; }
    { TERM=xterm-256color; tmux -f "${XDG_CONFIG_HOME}/tmux/tmux.conf" new-session -A -s "${TMUX_SESSION_ID}" -c "$HOME" && exit; } 
  else
    echo "tmux is not installed" 1>&2
  fi
fi

# load extra dotfiles
for file in "${BDOTDIR}"/env/*.bash; do
    source "${file}"
done

# eval "$(direnv hook zsh)"

